### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by fchristian1992** [johnoliver42/InvoiceMaker#1]
# Design/Code Review 1

### Reviewer: Frank Christian

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| -The problem and solution is as accurately stated as I feel it can be.<br> -The one typo I can see is a missing comma between "LibreOffice" and "the".<br> -As someone who knows nothing about business and invoices and such, I can confirm that an average person could understand it. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | -It seems navigable to me, although I notice that userHome and viewInvoices are oddly similar, assuming I'm not missing something. <br>-Form data is organized in a logical way <br>-All data seems to be in order.|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| -All data seems to be in order. <br>-There are numerous 1-to-many relationships.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  | -There's a lot of incomplete code, but what's there is good so far. <br>-Maven structure and gitignore is present and implemented. |

@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @fchristian1992 - thank you for your review. Catching the typo in the problem statement demonstrates that you reviewed that portion with a keen eye.

1. With regard to 

> I notice that userHome and viewInvoices are oddly similar, assuming I'm not missing something. 

Did you ask John for clarification on this during your review time?

**Comment by johnoliver42** [comment]
I sent Frank an explanation over Slack when I saw your response so I am assuming that this is taken care of. Can I close this issue?

**Comment by pawaitemadisoncollege** [comment]
Hi @johnoliver42, yes, if all issues identified have been addressed you can close this up.
