### ISSUE TITLE
Code review 1

### ISSUE THREAD

**Issue by kailynangelo** [johnoliver42/InvoiceMaker#3]
# Design/Code Review 1

### Reviewer: Kailyn Angelo

| Item | Considerations | Comments/Suggestions |

|--------|---------|---|

| Reviewer comments and suggestions go here. Each item should have
*at least* one "kudos" and two suggestions for improvement|

|**Problem Statement**| 1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| |

Great job with the problem statement. It meets the criteria mentioned above. One area for improvement would be describing the solution a little more thoroughly - the problem is very clear and elaborated on fully, and the solution is comparatively a little sparse. Another thing would be in the second paragraph, commenting what all information is needed to explain it's simplicity.

|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | |

Great job with this as well. When discussing the application during our meeting it sounded like things flowed a natural/logical order. One thing to improve would be adding labels to the form fields instead of just the default text to improve accessibility. Another thing could be using headers to make clear what the forms are could be useful to quickly tell what a given form's purpose is.  

|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| |

The database design looks thorough and seems to meet requirements. One possible improvement could be with the shipping table, extracting addresses to their own table and having the shipping table refer to addresses which could add functionality to store addresses as a possible future improvement. This could additionally be used in the business account address for the invoice table, maybe add an address type to the address table. 

|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.

The structure looks good, as well as .gitignore, resources, log4j implemented. Within src, there is no folder structure set up in main, only test. Add java folder for code in main with persistence, entity, appropriate structure for classes. Database/test classes look to be appropriately sized. Unit tests to be implemented. Overall great start, I look forward to seeing the finished product.

**Comment by johnoliver42** [comment]
Problem Statement: I have updated the problem statement but I don't think that I will add more details. This is a situation where the proof is in the pudding. Additionally, there isn't really anything unique about what the site does. The only thing that might be unique is that as a student project, I am adding multiple complex features.

Design Documentation: These are wireframes, not mockups. Wireframes don't need as many details. 

Data model/Database: I thought about adding a separate table for addresses. Having a feature where users could store addresses would be a nice add and if I ever manage to get ahead I think I will add it. However, the address still needs to be stored with the shipping data. If addresses for shipments were stored in a table that was being used as an "address book" what would happen to the shipment data if a user deleted an address? 

Thanks for your feedback Kailyn.

**Comment by pawaitemadisoncollege** [comment]
@kailynangelo Thanks for sharing your thoughtful here. Your feedback both identifies what's on target and provides considerations for improvement.  I noticed formatting here is a bit "off". The markdown table is not rendering correctly - you could either remove the pipes ` | ` to forgo the table or fix the pipes to show the table properly when viewed in github.  

@johnoliver42 Regarding "If addresses for shipments were stored in a table that was being used as an "address book" what would happen to the shipment data if a user deleted an address?" Could you define and implement a rule that prevents this from happening?

**Comment by johnoliver42** [comment]
@pawaitemadisoncollege Yes you could. But why would you? It would be better to store the address with the shipment and create an address book table separately for users to store addresses in. That way users could add/remove/update addresses in the address book without needing to maintain the original address used for the shipment.  

Imagine if a customer changed their address after you sent them a shipment and then claimed that you sent the original shipment to the wrong address. It's important to have a record of the original shipment that never changes once the shipment is mailed. 

It would be possible to add some additional fields to an address table that track if an address should be displayed in a user's address book and then another to track the version of the address if the address is used in a shipment. But that adds a lot of complexity to avoid adding a few text fields to a shipment table. 

Essentially, once a shipment is picked up by a carrier I think the shipment data used for the original label should be treated as an immutable record.

**Comment by pawaitemadisoncollege** [comment]
You absolutely right about using versions of addresses. In my experience that's what we did with addresses and lots of other data. We never deleted anything and had a change record/version history if something did change.  I can see how this might be too complex for your application at this point though!
