### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by shanda-matc** [johnoliver42/InvoiceMaker#4]
**Design/Code Review**
Project: InvoiceMaker
Developer: John Oliver
Reviewer: Shilpa Handa

| Item | Considerations | Comments/Suggestions |
| ---------------- | ---------------- | ---------------- |
|  | |Reviewer comments and suggestions go here. Each item should have at least one "kudos" and two suggestions for improvement|
|Problem Statement  | 1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person | 1. The problem statement accurately describes the project purpose<br>2. The problem statement is professional and it describes its functionality and benefits and free of typos and slangs<br>3. It's fully explains the problem and it's solution, which is creating invoices and shipping labels.<br>4. The problem statement is easy to understandable.  |
| Design Documentation | 1. Navigation/flow through the application is logical and easy to use.<br>2. The order in which values are displayed are logical and easy to understand/use<br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens  | Design Documentation looks good and seems easy to use. Everything looks good and easy to understand  |
| Data model/Database  | 1. Everything on the screens and problem statement/flow is represented in the model<br>2. There is at least one 1-to-many relationship.<br>3. The model represents good database design |Database design looks good as well and it has one to many relationship between users and user_roles etc.|
| Code |1. Proper Maven project structure is used<br>2. a .gitignore file for IntelliJ Java projects has been implemented<br>3. There is not any redundant or copy/paste code in the JSPs or classes<br>4. Classes are appropriately-sized (no monster classes)Property files are used appropriately: no hard-coded values<br>5. Logging statements are used rather than System.out.println and printStackTrace.<br>6. There are appropriate unit tests/code coverage. | The proper Maven project structure is used and .gitignore file for intelliJ is implemented. Everything looks good |

**Comment by pawaitemadisoncollege** [comment]
Hi @shanda-matc! Your feedback above does a good job providing kudos in the various categories, however I don't see any suggestions for improvement. Can you add some ideas here to help John improve his work?
